spring:
    application:
        name: realtime-chatapp-service-registery
server:
    port: 8761

eureka:
    instance:
        hostname: localhost
    client:
        fetch-registry: false
        register-with-eureka: false

management:
    tracing:
        sampling:
            probability: 1.0 # 100% sampling for development
    otlp:
        metrics:
            export:
                url: http://192.168.1.77:4318/v1/metrics
    opentelemetry:
        tracing:
            export:
                otlp:
                    endpoint: http://192.168.1.77:4318/v1/traces
        logging:
            export:
                otlp:
                    endpoint: http://192.168.1.77:4318/v1/logs
